### ISSUE TITLE
Thread Leak in BigQuerySinkTask.stop()

### ISSUE THREAD

**Issue by mjungsbluth** [wepay/kafka-connect-bigquery#117]
For operational simplicity we do create one Sink per Topic with a lot of topics. What we observed is that the Kafka Workers regularly run out of threads (> 32K Thread) which in turn makes the system itself inaccessible.

In `BigQuerySinkTask.stop()` the `executor.shutdown()` method should be called. 

This is really bad since this means that even connector restarts and every rebalance increase the thread count. 

We fixed this locally and verified that this indeed alleviates the problem. 

A general question though: Why use a thread pool for every task at all? Are other connectors doing this as well? Why not just increase the task.max config and let kafka connect handle it?

**Comment by jgao54** [comment]
Hi @mjungsbluth, AFAIK in the past we actually did not have a thread pool, and `flush` would do all the work of uploading data to BQ. This resulted in timeout issues in the `flush` method. So to circumvent this (while not blocking traffic), we migrated the workload from `flush` to `put` by adding a thread pool that kicks off the work immediately rather than waiting for the task to be flushed. 

I think you are right, `executor.shutdown()` should be called upon `stop`.

**Comment by criccomini** [comment]
> Why not just increase the task.max config and let kafka connect handle it?
The task max is going to be limited to the number of partitions in Kafka. If you need more throughput (i.e. more parallel threads inserting into BQ) than the number of partitions, you have to use a thread pool.

**Comment by criccomini** [comment]
Fixed in https://github.com/wepay/kafka-connect-bigquery/pull/119
