### ISSUE TITLE
Duplicated records

### ISSUE THREAD

**Issue by infinex** [wepay/kafka-connect-bigquery#96]
I am getting duplicated records in big query compared to the offsets in kafka for the same topic. Is this an an expected results? Thanks!

**Comment by mtagle** [comment]
Hey infinex, that doesn't sound like an expected result in general.  Is every single record being duplicated, or just some? Is there any additional detail you can give us?

My immediate thought is that you may be seeing duplicate records if your connector is encountering a lot of errors. If the connector encounters an error when sending rows to BQ, it will retry those rows, because it has no way of evaluating if some of those rows succeeded.

However, I will note that kcbq doesn't promise only once delivery. If it's really important that you not see duplicate rows in BQ, the best solution would be implement some sort of deduplicated view within BQ.

**Comment by infinex** [comment]
Hi mtagle, it is some of the records being duplicated. I will try to deduplicate from the BQ side.Thanks!
